### ISSUE TITLE
build issues

### ISSUE THREAD

**Issue by stuarteberg** [DerThorsten/nifty#25]
I tried building the conda recipe using the latest master.  I ran into the following issues:

- I needed to manually update the `externals/pybind11` source code.  (Otherwise, I get an error about `py::exception` not defined)

- On Mac, at least, the `_nifty.so` python extension module isn't linked correctly.  It is missing references to `libgurobi65.so`, `libpython2.7.so`, and also hdf5.  This seems to be due to 35432bbd522f9436b65aaae7bcb45ad7563fd087.  When I added those `target_link_libraries` lines back in, the linking is correct again.

- The conda recipe was missing a requirement for `futures`.  Easy fix.

I'm now stuck on this error:

```pytb
===== testing package: nifty-with-gurobi-0.3b1.post28-py27_0_g14d2a68 =====
import: u'nifty_with_gurobi'
Traceback (most recent call last):
  File "/miniconda2/conda-bld/conda-recipe_1480628560811/test_tmp/run_test.py", line 27, in <module>
    import nifty_with_gurobi
  File "/miniconda2/conda-bld/conda-recipe_1480628560811/_t_env/lib/python2.7/site-packages/nifty_with_gurobi/__init__.py", line 16, in <module>
    import ufd
  File "/miniconda2/conda-bld/conda-recipe_1480628560811/_t_env/lib/python2.7/site-packages/nifty_with_gurobi/ufd/__init__.py", line 1, in <module>
    from _ufd import *
ImportError: generic_type: cannot initialize type "Ufd": an object with that name is already defined
```

**Comment by DerThorsten** [comment]
I guess this can be closed? I think these things should not be an issue any more
