### ISSUE TITLE
The nifty can not run successfully without CPLEX?

### ISSUE THREAD

**Issue by jy9387** [DerThorsten/nifty#66]
Hi. I wonder whether the nifty module could run without the CPLEX, cause I have the AssertionError below when I run the main.py of lifted_fuion_moves_eccv_2016:
'''
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import segmentation_pipeline as segp
  File "/home/jiangyuan/lifted_fusion_moves_eccv_2016/segmentation_pipeline/__init__.py", line 19, in <module>
    assert nifty.Configuration.WITH_CPLEX
AssertionError
'''

**Comment by DerThorsten** [comment]
It can run without Cplex, but certain solvers need cplex.
